/*
 * 
 * This unpublished source code contains trade secrets and copyrighted
 * materials that are the proprietary property of iseemedia, Inc.
 * Unauthorized use, copying or distribution of this source code or the
 * ideas contained herein is a violation of U.S. and international laws
 * and is strictly prohibited.
 *
 * Copyright (c) 2005 iseemedia, Inc. All Rights Reserved.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.27 at 05:09:58 PM EDT 
//


package cg.publish.xmlbinding.ftpusers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cg.iseepublish.xmlbinding.ftpusers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FtpUsers_QNAME = new QName("", "ftpUsers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cg.iseepublish.xmlbinding.ftpusers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FtpUserType }
     * 
     */
    public FtpUserType createFtpUserType() {
        return new FtpUserType();
    }

    /**
     * Create an instance of {@link FtpUsersType }
     * 
     */
    public FtpUsersType createFtpUsersType() {
        return new FtpUsersType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FtpUsersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ftpUsers")
    public JAXBElement<FtpUsersType> createFtpUsers(FtpUsersType value) {
        return new JAXBElement<FtpUsersType>(_FtpUsers_QNAME, FtpUsersType.class, null, value);
    }

}
