//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.05 at 11:27:00 AM EDT 
//


package cg.publish.xmlbinding.ftpConfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.ftpConfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FtpConnectionInfos_QNAME = new QName("", "ftpConnectionInfos");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.ftpConfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FtpConnectionInfos }
     * 
     */
    public FtpConnectionInfos createFtpConnectionInfos() {
        return new FtpConnectionInfos();
    }

    /**
     * Create an instance of {@link FtpConnectionInfo }
     * 
     */
    public FtpConnectionInfo createFtpConnectionInfo() {
        return new FtpConnectionInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FtpConnectionInfos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ftpConnectionInfos")
    public JAXBElement<FtpConnectionInfos> createFtpConnectionInfos(FtpConnectionInfos value) {
        return new JAXBElement<FtpConnectionInfos>(_FtpConnectionInfos_QNAME, FtpConnectionInfos.class, null, value);
    }

}
